.TH "AbstractTable.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractTable.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'TableState\&.h'\fP
.br
\fC#include 'CustomerGroup\&.h'\fP
.br
\fC#include 'Order\&.h'\fP
.br
\fC#include 'Review\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractTable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
