.TH "BillCaretaker.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BillCaretaker.h \- Declaration of the \fBBillCaretaker\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'BillMemento\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBillCaretaker\fP"
.br
.RI "Manages the storage and retrieval of bill Memento objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBBillCaretaker\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
