.TH "CustomerGroup.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomerGroup.h \- Declaration of the \fBCustomerGroup\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Customer\&.h'\fP
.br
\fC#include 'Order\&.h'\fP
.br
\fC#include 'Review\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomerGroup\fP"
.br
.RI "Represents a group of customers in a restaurant\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBCustomerGroup\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
