.TH "FoodItem" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoodItem \- Represents a food item with name, price, preparation method, and type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoodItem\fP (string, int, string, string)"
.br
.ti -1c
.RI "\fB~FoodItem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBprice\fP"
.br
.ti -1c
.RI "string \fBmethod\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a food item with name, price, preparation method, and type\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FoodItem::FoodItem (string, int, string, string)"

.SS "FoodItem::~FoodItem ()"

.SH "Member Data Documentation"
.PP 
.SS "string FoodItem::method"
The preparation method of the food item\&. 
.SS "string FoodItem::name"
The name of the food item\&. 
.SS "int FoodItem::price"
The price of the food item\&. 
.SS "string FoodItem::type"
The type of food item (e\&.g\&., \fBBurger\fP, \fBPasta\fP, etc\&.)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
