.TH "RandomString" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomString \- The \fBRandomString\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RandomString\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBPositiveComment\fP [10]"
.br
.RI "An array of positive comments\&. "
.ti -1c
.RI "static string \fBNegativeComment\fP [10]"
.br
.RI "An array of negative comments\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBRandomString\fP class\&. 

This class represents a collection of positive and negative comments about a restaurant\&. 
.SH "Member Data Documentation"
.PP 
.SS "string RandomString::NegativeComment[10]\fC [static]\fP"

.PP
An array of negative comments\&. 
.SS "string RandomString::PositiveComment[10]\fC [static]\fP"

.PP
An array of positive comments\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
