.TH "ReadyToOrder.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadyToOrder.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'TableState\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReadyToOrder\fP"
.br
.RI "A class that represents the state of a table when it is ready to order\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
