.TH "TableState.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableState.h \- Header file for the \fBTableState\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTableState\fP"
.br
.RI "The \fBTableState\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBTableState\fP class\&. 

This file contains the declaration of the \fBTableState\fP class\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
