.TH "BillMemento.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BillMemento.h \- Declaration of the \fBBillMemento\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'BillState\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBillMemento\fP"
.br
.RI "Represents a Memento for storing the state of a bill\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBBillMemento\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
