.TH "CombinedTable.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CombinedTable.h \- Declaration of the \fBCombinedTable\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'AbstractTable\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Order\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCombinedTable\fP"
.br
.RI "Represents a combined table that can group multiple \fBAbstractTable\fP instances\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBCombinedTable\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
