.TH "Happy" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Happy \- The \fBHappy\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Happy\&.h>\fP
.PP
Inherits \fBCustomerState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBgetStatus\fP ()"
.br
.RI "Get the status of the customer\&. "
.ti -1c
.RI "void \fBaction\fP ()"
.br
.RI "Perform the action for the \fBHappy\fP state\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBHappy\fP class\&. 

This class represents the \fBHappy\fP state of a customer\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Happy::action ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Perform the action for the \fBHappy\fP state\&. 
.PP
Implements \fBCustomerState\fP\&.
.SS "string Happy::getStatus ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the status of the customer\&. 
.PP
\fBReturns\fP
.RS 4
The status of the customer\&. 
.RE
.PP

.PP
Implements \fBCustomerState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
