.TH "Pasta.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pasta.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./Food\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPasta\fP"
.br
.RI "The \fBPasta\fP class represents a generic pasta dish\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
