make:
	g++ -std=c++17 -g *.cpp -o main

run:
	make
	./main
	make clean

macrun:
	g++-11 -std=c++17 -g *.cpp -o main
	./main
	make clean

clean:
	rm ./main

full-clean:
	rm *.o *.tar  main

clean-o:
	rm *.o

	