.TH "Angry.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Angry.h \- Declaration of the \fBAngry\fP class, a subclass of \fBCustomerState\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CustomerState\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAngry\fP"
.br
.RI "Represents the 'Angry' state of a customer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBAngry\fP class, a subclass of \fBCustomerState\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
