.TH "Bill.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bill.h \- Declaration of the \fBBill\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'BillState\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'BillMemento\&.h'\fP
.br
\fC#include 'Order\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBill\fP"
.br
.RI "Represents a bill associated with a customer's order\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declaration of the \fBBill\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
