.TH "Carbonara.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carbonara.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PastaType\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCarbonara\fP"
.br
.RI "The \fBCarbonara\fP class represents \fBCarbonara\fP pasta, which is a specific type of \fBPastaType\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
