.TH "Floor.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Floor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Waiter\&.h'\fP
.br
\fC#include 'Employee\&.h'\fP
.br
\fC#include 'Manager\&.h'\fP
.br
\fC#include 'Iterator\&.h'\fP
.br
\fC#include 'Table\&.h'\fP
.br
\fC#include 'CombinedTable\&.h'\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFloor\fP"
.br
.RI "This is the interface for floor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
