.TH "MargheritaPizza.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MargheritaPizza.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PizzaType\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMargheritaPizza\fP"
.br
.RI "The \fBMargheritaPizza\fP class represents a Margherita pizza type, which is a specific type of \fBPizza\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
