.TH "Menu.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFoodItem\fP"
.br
.RI "Represents a food item with name, price, preparation method, and type\&. "
.ti -1c
.RI "class \fBMenu\fP"
.br
.RI "Represents a menu for a restaurant\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
