.TH "NotReadyToOrder" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotReadyToOrder \- The \fBNotReadyToOrder\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NotReadyToOrder\&.h>\fP
.PP
Inherits \fBTableState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBgetStatus\fP ()"
.br
.RI "Get the status of the table\&. "
.ti -1c
.RI "bool \fBaction\fP ()"
.br
.RI "Perform the action for the \fBNotReadyToOrder\fP status\&. "
.in -1c

Public Member Functions inherited from \fBTableState\fP
.in +1c
.ti -1c
.RI "\fBTableState\fP ()"
.br
.RI "Construct a new \fBTableState\fP object\&. "
.ti -1c
.RI "void \fBsetTable\fP (\fBAbstractTable\fP *\fBtable\fP)"
.br
.RI "Set the table\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBTableState\fP
.in +1c
.ti -1c
.RI "\fBAbstractTable\fP * \fBtable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBNotReadyToOrder\fP class\&. 

This class represents the \fBNotReadyToOrder\fP status of a table\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool NotReadyToOrder::action ()\fC [virtual]\fP"

.PP
Perform the action for the \fBNotReadyToOrder\fP status\&. 
.PP
\fBReturns\fP
.RS 4
True if the action was successful, false otherwise\&. 
.RE
.PP

.PP
Implements \fBTableState\fP\&.
.SS "string NotReadyToOrder::getStatus ()\fC [virtual]\fP"

.PP
Get the status of the table\&. 
.PP
\fBReturns\fP
.RS 4
The status of the table\&. 
.RE
.PP

.PP
Implements \fBTableState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
