.TH "OnionTopping.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OnionTopping.h
.SH SYNOPSIS
.br
.PP
\fC#include 'BurgerTopping\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOnionTopping\fP"
.br
.RI "The \fBOnionTopping\fP class represents an onion topping for a burger, which is a specific type of \fBBurgerTopping\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
