.TH "Order.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Order.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'OrderStatus\&.h'\fP
.br
\fC#include 'Ready\&.h'\fP
.br
\fC#include 'Processing\&.h'\fP
.br
\fC#include 'Received\&.h'\fP
.br
\fC#include 'Menu\&.h'\fP
.br
\fC#include 'Food\&.h'\fP
.br
\fC#include 'Employee\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOrder\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
