.TH "PastaType.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PastaType.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Pasta\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPastaType\fP"
.br
.RI "The \fBPastaType\fP class represents a specific type of pasta, which is a type of \fBPasta\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
