.TH "pastaBase.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pastaBase.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Pasta\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpastaBase\fP"
.br
.RI "The \fBpastaBase\fP class represents the base of a pasta dish, which is a specific type of \fBPasta\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
