.TH "PepperoniPizza.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PepperoniPizza.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PizzaType\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPepperoniPizza\fP"
.br
.RI "The \fBPepperoniPizza\fP class represents a Pepperoni pizza type, which is a specific type of \fBPizza\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
