.TH "PizzaType.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PizzaType.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Pizza\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPizzaType\fP"
.br
.RI "The \fBPizzaType\fP class represents a specific type of pizza, which is a type of \fBPizza\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
