.TH "PizzaType" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PizzaType \- The \fBPizzaType\fP class represents a specific type of pizza, which is a type of \fBPizza\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PizzaType\&.h>\fP
.PP
Inherits \fBPizza\fP\&.
.PP
Inherited by \fBMargheritaPizza\fP, \fBMeatSupremePizza\fP, and \fBPepperoniPizza\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPizzaType\fP ()"
.br
.RI "Constructor for \fBPizzaType\fP\&. "
.ti -1c
.RI "virtual double \fBtotal\fP ()"
.br
.RI "Returns the total cost of the pizza\&. "
.ti -1c
.RI "virtual void \fBdecorate\fP (\fBPizza\fP *pizzaType)"
.br
.RI "Decorates the pizza\&. "
.in -1c

Public Member Functions inherited from \fBPizza\fP
.in +1c
.ti -1c
.RI "\fBPizza\fP ()"
.br
.RI "Constructor for \fBPizza\fP to set its cost to 0\&.0\&. "
.ti -1c
.RI "double \fBgetCost\fP ()"
.br
.RI "Get the cost of the pizza\&. "
.ti -1c
.RI "void \fBsetCost\fP (double cost)"
.br
.RI "Set the cost of the pizza\&. "
.ti -1c
.RI "virtual \fB~Pizza\fP ()"
.br
.RI "Virtual destructor for \fBPizza\fP\&. "
.in -1c

Public Member Functions inherited from \fBFood\fP
.in +1c
.ti -1c
.RI "\fBFood\fP ()"
.br
.RI "Construct a new \fBFood\fP object\&. "
.ti -1c
.RI "void \fBsetFoodQuality\fP (int)"
.br
.ti -1c
.RI "int \fBgetFoodQuality\fP ()"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (string \fBname\fP)"
.br
.ti -1c
.RI "void \fBaddIngredient\fP (string ingredient)"
.br
.ti -1c
.RI "double \fBgetCost\fP ()"
.br
.ti -1c
.RI "void \fBsetCost\fP (double \fBcost\fP)"
.br
.ti -1c
.RI "virtual \fB~Food\fP ()"
.br
.ti -1c
.RI "virtual void \fBdecorate\fP (\fBBurger\fP *)"
.br
.ti -1c
.RI "virtual void \fBdecorate\fP (\fBPasta\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB~PizzaType\fP ()"
.br
.RI "Destructor for \fBPizzaType\fP\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBFood\fP
.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "vector< string > \fBingredients\fP"
.br
.ti -1c
.RI "int \fBRandomFoodQuality\fP"
.br
.ti -1c
.RI "double \fBcost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPizzaType\fP class represents a specific type of pizza, which is a type of \fBPizza\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PizzaType::PizzaType ()"

.PP
Constructor for \fBPizzaType\fP\&. 
.SS "PizzaType::~PizzaType ()\fC [protected]\fP"

.PP
Destructor for \fBPizzaType\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void PizzaType::decorate (\fBPizza\fP * pizzaType)\fC [virtual]\fP"

.PP
Decorates the pizza\&. 
.PP
\fBParameters\fP
.RS 4
\fIpizzaType\fP A pointer to the \fBPizza\fP to be decorated\&. 
.RE
.PP

.PP
Implements \fBPizza\fP\&.
.SS "virtual double PizzaType::total ()\fC [virtual]\fP"

.PP
Returns the total cost of the pizza\&. 
.PP
\fBReturns\fP
.RS 4
The total cost of the pizza\&. 
.RE
.PP

.PP
Implements \fBPizza\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
