.TH "PizzaBase.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PizzaBase.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Pizza\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPizzaBase\fP"
.br
.RI "The \fBPizzaBase\fP class represents the base of a pizza, which is a specific type of \fBPizza\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
