.TH "Ready" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ready \- The \fBReady\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ready\&.h>\fP
.PP
Inherits \fBOrderStatus\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBgetStatus\fP ()"
.br
.RI "Get the status of the order\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBReady\fP class\&. 

This class represents the \fBReady\fP status of an order\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual string Ready::getStatus ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the status of the order\&. 
.PP
\fBReturns\fP
.RS 4
The status of the order\&. 
.RE
.PP

.PP
Implements \fBOrderStatus\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
