.TH "Spaghetti.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Spaghetti.h
.SH SYNOPSIS
.br
.PP
\fC#include 'pastaBase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpaghetti\fP"
.br
.RI "The \fBSpaghetti\fP class represents spaghetti pasta, which is a specific type of PastaBase\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
