.TH "ThickBasePizza" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThickBasePizza \- The \fBThickBasePizza\fP class represents a pizza with a thick crust base, which is a specific type of \fBPizzaBase\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ThickBasePizza\&.h>\fP
.PP
Inherits \fBPizzaBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThickBasePizza\fP ()"
.br
.RI "Constructor for \fBThickBasePizza\fP to set its name and cost\&. "
.in -1c

Public Member Functions inherited from \fBPizzaBase\fP
.in +1c
.ti -1c
.RI "\fBPizzaBase\fP ()"
.br
.RI "Constructor for \fBPizzaBase\fP\&. "
.ti -1c
.RI "virtual double \fBtotal\fP ()"
.br
.RI "Returns the total cost of the pizza\&. "
.ti -1c
.RI "virtual void \fBdecorate\fP (\fBPizza\fP *)"
.br
.RI "Decorates the pizza\&. "
.ti -1c
.RI "\fB~PizzaBase\fP ()"
.br
.RI "Destructor for \fBPizzaBase\fP\&. "
.in -1c

Public Member Functions inherited from \fBPizza\fP
.in +1c
.ti -1c
.RI "\fBPizza\fP ()"
.br
.RI "Constructor for \fBPizza\fP to set its cost to 0\&.0\&. "
.ti -1c
.RI "double \fBgetCost\fP ()"
.br
.RI "Get the cost of the pizza\&. "
.ti -1c
.RI "void \fBsetCost\fP (double cost)"
.br
.RI "Set the cost of the pizza\&. "
.ti -1c
.RI "virtual \fB~Pizza\fP ()"
.br
.RI "Virtual destructor for \fBPizza\fP\&. "
.in -1c

Public Member Functions inherited from \fBFood\fP
.in +1c
.ti -1c
.RI "\fBFood\fP ()"
.br
.RI "Construct a new \fBFood\fP object\&. "
.ti -1c
.RI "void \fBsetFoodQuality\fP (int)"
.br
.ti -1c
.RI "int \fBgetFoodQuality\fP ()"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (string \fBname\fP)"
.br
.ti -1c
.RI "void \fBaddIngredient\fP (string ingredient)"
.br
.ti -1c
.RI "double \fBgetCost\fP ()"
.br
.ti -1c
.RI "void \fBsetCost\fP (double \fBcost\fP)"
.br
.ti -1c
.RI "virtual \fB~Food\fP ()"
.br
.ti -1c
.RI "virtual void \fBdecorate\fP (\fBBurger\fP *)"
.br
.ti -1c
.RI "virtual void \fBdecorate\fP (\fBPasta\fP *)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBFood\fP
.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "vector< string > \fBingredients\fP"
.br
.ti -1c
.RI "int \fBRandomFoodQuality\fP"
.br
.ti -1c
.RI "double \fBcost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBThickBasePizza\fP class represents a pizza with a thick crust base, which is a specific type of \fBPizzaBase\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ThickBasePizza::ThickBasePizza ()"

.PP
Constructor for \fBThickBasePizza\fP to set its name and cost\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
