.TH "ThinBasePizza.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThinBasePizza.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PizzaBase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThinBasePizza\fP"
.br
.RI "The \fBThinBasePizza\fP class represents a pizza with a thin crust base, which is a specific type of \fBPizzaBase\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
