.TH "Waiter.h" 3 "Cheat GBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Waiter.h
.SH SYNOPSIS
.br
.PP
\fC#include 'TableIterator\&.h'\fP
.br
\fC#include 'Employee\&.h'\fP
.br
\fC#include 'Order\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWaiter\fP"
.br
.RI "Represents a waiter who takes and delivers orders in a restaurant\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cheat GBT from the source code\&.
