name: Build and Run C++

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: set-up-gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: clean-prev
        run: |
          cd test-project/Implementation; make full-clean

      - name: build-cpp
        run: |
          cd test-project/Implementation; make

      - name: clean-object-files
        run: |
          cd test-project/Implementation; make clean-o
