name: Build and Run C++

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: set-up-gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: cd-Implementation
        run: |
          cd Implementation

      - name: clean-prev
        run: |
          make full-clean

      - name: build-cpp
        run: |
          make

      - name: move-binary
        run: |
          mv main ../

      - name: clean-object-files
        run: |
          make clean-o
